---
title: "Group Project"
author: "Beau Belkowski, Brian Marquardt, Danny Buglak"
date: '2024-02-27'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(cluster)
library(ggplot2)
library(factoextra)
library(corrplot)
```

```{r}
getwd()
#y2021 <- read.csv("2021.csv")
```

```{r}
y2021 <- read.csv("2021.csv")
y2019 <- read.csv("2019.csv")
y2018 <- read.csv("2018.csv")
y2017 <- read.csv("2017.csv")
y2016 <- read.csv("2016.csv")

y2021
y2019
y2018
y2017
y2016
```

```{r}
y2021$G <- as.double(y2021$G)
y2021$GS <- as.double(y2021$GS)
y2021$Age <- as.double(y2021$Age)
#y2021
```

```{r}
y2021$year<- rep('2021', times= nrow(y2021))
y2021.1 <- y2021[,-1]
#y2021.1
y2018$year<- rep('2018', times= nrow(y2018))
y2018.1 <- y2018[,-1]
#y2018.1
y2019$year<- rep('2019', times= nrow(y2019))
y2019.1 <- y2019[,-1]
#y2019.1
y2017$year<- rep('2017', times= nrow(y2017))
y2017.1 <- y2017[,-1]
#y2017.1
y2016$year<- rep('2016', times= nrow(y2016))
y2016.1 <- y2016[,-1]
#y2016.1


fb <- rbind(y2021.1, y2019.1, y2018.1, y2017.1, y2016.1)
#fb
```
```{r}
fb$Tgt_gm <- fb$Tgt/fb$G
fb$Rec_gm <- fb$Rec/fb$G
fb$PassingYds_gm <- fb$PassingYds/fb$G
fb$PassingTD_gm <- fb$PassingTD/fb$G
fb$PassingAtt_gm <- fb$PassingAtt/fb$G
fb$RushingYds_gm <- fb$RushingYds/fb$G
fb$RushingTD_gm <- fb$RushingTD/fb$G
fb$RushingAtt_gm <- fb$RushingAtt/fb$G
fb$ReceivingYds_gm <- fb$ReceivingYds/fb$G
fb$ReceivingTD_gm <- fb$ReceivingTD/fb$G
fb$FantasyPoints_gm <- fb$FantasyPoints/fb$G
fb$Int_gm <- fb$Int/fb$G
fb$Fumbles_gm <- fb$Fumbles/fb$G
fb$FumblesLost_gm <- fb$FumblesLost/fb$G
summary(fb)
```

```{r}
fb1 <- fb %>%
  filter(GS >= 5, FantasyPoints_gm > 0)
fb1
```


```{r}
rb <- fb1 %>%
  filter(Pos == "RB")
qb <- fb1 %>%
  filter(Pos == "QB")
wr <- fb1 %>%
  filter(Pos == "WR")
te <- fb1 %>%
  filter(Pos == "TE")
rb
qb
wr
te
```

```{r}

ggplot(data = fb1, aes(x = FantasyPoints_gm)) + 
  geom_histogram() +
  ggtitle("Distribution of Fantasy Points per Game")

ggplot(data = rb, aes(x = RushingYds_gm)) + 
  geom_histogram() +
  ggtitle("Distribution of Runningbacks Rushing Yards per Game")

ggplot(data = qb, aes(x = PassingTD_gm)) + 
  geom_histogram() +
  ggtitle("Distribution of Quarterbacks Passing Touchdowns per Game")

ggplot(data = rb, aes(x = FantasyPoints_gm, y = RushingYds_gm)) + 
  geom_point() +
  ggtitle("Correlation for Running Backs Fantasy Points per Game and Rushing Yards per Game")

ggplot(data = fb1, aes(x = FantasyPoints_gm, y = FumblesLost_gm)) + 
  geom_point() +
  ggtitle("Correlation Between Fantasy Points per Game and Fumbles Lost per Game")

ggplot(data = wr, aes(x = FantasyPoints_gm, y = ReceivingTD_gm)) + 
  geom_point() +
  ggtitle("Correlation for Wide Recievers Fantasy Points per Game and Recieving Touchdowns per Game")
```
```{r}
rb1 <- rb %>%
  filter(RushingYds_gm == 0)
rb1
```

```{r}
qb_gm <- qb %>%
  select(Player, Tm, Pos, Age, G, GS, , year, Tgt_gm, Rec_gm, PassingYds_gm, PassingTD_gm, PassingAtt_gm, RushingYds_gm, RushingTD_gm, RushingAtt_gm, ReceivingYds_gm, ReceivingTD_gm, FantasyPoints_gm, Int_gm, Fumbles_gm, FumblesLost_gm)

rb_gm <- rb %>%
  select(Player, Tm, Pos, Age, G, GS, , year, Tgt_gm, Rec_gm, PassingYds_gm, PassingTD_gm, PassingAtt_gm, RushingYds_gm, RushingTD_gm, RushingAtt_gm, ReceivingYds_gm, ReceivingTD_gm, FantasyPoints_gm, Int_gm, Fumbles_gm, FumblesLost_gm)

wr_gm <- wr %>%
  select(Player, Tm, Pos, Age, G, GS, , year, Tgt_gm, Rec_gm, PassingYds_gm, PassingTD_gm, PassingAtt_gm, RushingYds_gm, RushingTD_gm, RushingAtt_gm, ReceivingYds_gm, ReceivingTD_gm, FantasyPoints_gm, Int_gm, Fumbles_gm, FumblesLost_gm)

te_gm <- te %>%
  select(Player, Tm, Pos, Age, G, GS, , year, Tgt_gm, Rec_gm, PassingYds_gm, PassingTD_gm, PassingAtt_gm, RushingYds_gm, RushingTD_gm, RushingAtt_gm, ReceivingYds_gm, ReceivingTD_gm, FantasyPoints_gm, Int_gm, Fumbles_gm, FumblesLost_gm)
```


```{r}

qbcorr <- subset(qb_gm, select = -c(Tm, Pos, Player, year))
corrplot(cor(qbcorr), method ="circle")

rbcorr <- subset(rb_gm, select = -c(Tm, Pos, Player, year))
corrplot(cor(rbcorr), method ="circle")

wrcorr <- subset(wr_gm, select = -c(Tm, Pos, Player, year))
corrplot(cor(wrcorr), method ="circle")

tecorr <- subset(te_gm, select = -c(Tm, Pos, Player, year))
corrplot(cor(tecorr), method ="circle")
```
```{r}
# Most highly correlated stats with qb success
cor(qb_gm$FantasyPoints_gm, qb_gm$PassingTD_gm)
cor(qb_gm$FantasyPoints_gm, qb_gm$PassingYds_gm)
cor(qb_gm$FantasyPoints_gm, qb_gm$GS)
cor(qb_gm$FantasyPoints_gm, qb_gm$PassingAtt_gm)
```

```{r}
ggplot(qb_gm, aes(x = FantasyPoints_gm, y = PassingTD_gm)) + 
  geom_point()+ 
  geom_smooth(method=lm, se=FALSE, fullrange=TRUE)

ggplot(qb_gm, aes(x = FantasyPoints_gm, y = PassingYds_gm)) + 
  geom_point()+ 
  geom_smooth(method=lm, se=FALSE, fullrange=TRUE)

ggplot(qb_gm, aes(x = FantasyPoints_gm, y = GS)) + 
  geom_point()+ 
  geom_smooth(method=lm, se=FALSE, fullrange=TRUE)

ggplot(qb_gm, aes(x = FantasyPoints_gm, y = PassingAtt_gm)) + 
  geom_point()+ 
  geom_smooth(method=lm, se=FALSE, fullrange=TRUE)
```


```{r}
# Most highly correlated stats with rb success
cor(rb_gm$FantasyPoints_gm, rb_gm$Tgt_gm)
cor(rb_gm$FantasyPoints_gm, rb_gm$Rec_gm)
cor(rb_gm$FantasyPoints_gm, rb_gm$RushingYds_gm)
cor(rb_gm$FantasyPoints_gm, rb_gm$RushingTD_gm)
cor(rb_gm$FantasyPoints_gm, rb_gm$RushingAtt_gm)
cor(rb_gm$FantasyPoints_gm, rb_gm$ReceivingYds_gm)
cor(rb_gm$FantasyPoints_gm, rb_gm$ReceivingTD_gm)
cor(rb_gm$FantasyPoints_gm, rb_gm$GS)
```

```{r}
ggplot(rb_gm, aes(x = FantasyPoints_gm, y = Tgt_gm)) + 
  geom_point()+ 
  geom_smooth(method=lm, se=FALSE, fullrange=TRUE)

ggplot(rb_gm, aes(x = FantasyPoints_gm, y = Rec_gm)) + 
  geom_point()+ 
  geom_smooth(method=lm, se=FALSE, fullrange=TRUE)

ggplot(rb_gm, aes(x = FantasyPoints_gm, y = RushingYds_gm)) + 
  geom_point()+ 
  geom_smooth(method=lm, se=FALSE, fullrange=TRUE)

ggplot(rb_gm, aes(x = FantasyPoints_gm, y = RushingTD_gm)) + 
  geom_point()+ 
  geom_smooth(method=lm, se=FALSE, fullrange=TRUE)

ggplot(rb_gm, aes(x = FantasyPoints_gm, y = RushingAtt_gm)) + 
  geom_point()+ 
  geom_smooth(method=lm, se=FALSE, fullrange=TRUE)

ggplot(rb_gm, aes(x = FantasyPoints_gm, y = ReceivingYds_gm)) + 
  geom_point()+ 
  geom_smooth(method=lm, se=FALSE, fullrange=TRUE)

ggplot(rb_gm, aes(x = FantasyPoints_gm, y = ReceivingTD_gm)) + 
  geom_point()+ 
  geom_smooth(method=lm, se=FALSE, fullrange=TRUE)

ggplot(rb_gm, aes(x = FantasyPoints_gm, y = GS)) + 
  geom_point()+ 
  geom_smooth(method=lm, se=FALSE, fullrange=TRUE)
```

```{r}
# Most highly correlated stats with wr success
cor(wr_gm$FantasyPoints_gm, wr_gm$GS)
cor(wr_gm$FantasyPoints_gm, wr_gm$Tgt_gm)
cor(wr_gm$FantasyPoints_gm, wr_gm$Rec_gm)
cor(wr_gm$FantasyPoints_gm, wr_gm$ReceivingTD_gm)
cor(wr_gm$FantasyPoints_gm, wr_gm$ReceivingYds_gm)
```

```{r}
ggplot(wr_gm, aes(x = FantasyPoints_gm, y = GS)) + 
  geom_point()+ 
  geom_smooth(method=lm, se=FALSE, fullrange=TRUE)

ggplot(wr_gm, aes(x = FantasyPoints_gm, y = Tgt_gm)) + 
  geom_point()+ 
  geom_smooth(method=lm, se=FALSE, fullrange=TRUE)

ggplot(wr_gm, aes(x = FantasyPoints_gm, y = Rec_gm)) + 
  geom_point()+ 
  geom_smooth(method=lm, se=FALSE, fullrange=TRUE)

ggplot(wr_gm, aes(x = FantasyPoints_gm, y = ReceivingTD_gm)) + 
  geom_point()+ 
  geom_smooth(method=lm, se=FALSE, fullrange=TRUE)

ggplot(wr_gm, aes(x = FantasyPoints_gm, y = ReceivingYds_gm)) + 
  geom_point()+ 
  geom_smooth(method=lm, se=FALSE, fullrange=TRUE)
```

```{r}
# Most highly correlated stats with te success
cor(te_gm$FantasyPoints_gm, te_gm$Tgt_gm)
cor(te_gm$FantasyPoints_gm, te_gm$Rec_gm)
cor(te_gm$FantasyPoints_gm, te_gm$ReceivingTD_gm)
cor(te_gm$FantasyPoints_gm, te_gm$ReceivingYds_gm)
```

```{r}
ggplot(te_gm, aes(x = FantasyPoints_gm, y = Tgt_gm)) + 
  geom_point()+ 
  geom_smooth(method=lm, se=FALSE, fullrange=TRUE)

ggplot(te_gm, aes(x = FantasyPoints_gm, y = Rec_gm)) + 
  geom_point()+ 
  geom_smooth(method=lm, se=FALSE, fullrange=TRUE)

ggplot(te_gm, aes(x = FantasyPoints_gm, y = ReceivingTD_gm)) + 
  geom_point()+ 
  geom_smooth(method=lm, se=FALSE, fullrange=TRUE)

ggplot(te_gm, aes(x = FantasyPoints_gm, y = ReceivingYds_gm)) + 
  geom_point()+ 
  geom_smooth(method=lm, se=FALSE, fullrange=TRUE)
```









## Clustering Analysis

```{r}
set.seed(20)

# Remove name and team and omit any NA values
clust_fb <- fb1 %>% 
  select(-c("Player", "Tm")) %>%
  na.omit()

# Scale the data to normalize it
normalized_fb <- scale(clust_fb[, sapply(clust_fb, is.numeric)])

# Determine the optimal number of clusters using Elbow method
elbow <- sapply(1:15, function(k) {
  kmeans(normalized_fb, centers = k, nstart = 50)$tot.withinss
  })
plot(1:15, elbow, type="b", xlab="Number of Clusters", ylab="Within groups sum of squares")
```

Elbow Method shows that 4 is the optimal number of clusters. This is because 4 is when the line on the graph "elbows", or where it begins to shallow out and adding any more clusters than 4 do not change the analysis by much.

```{r cluster-creation}
set.seed(20)

# Performs k means on normalized data set
k <- kmeans(normalized_fb, centers = 4)

# Add cluster information to original data set
clust_fb$cluster <- k$cluster

# For factor or character variables, use table to get counts for each cluster
position_counts <- table(clust_fb$cluster, clust_fb$Pos)

get_mode <- function(x) {
  ux <- unique(x)
  ux[which.max(tabulate(match(x, ux)))]
}

# Apply the custom mode function to get the most common position per cluster
common_positions <- tapply(clust_fb$Pos, clust_fb$cluster, get_mode)
common_positions

# First, create a data frame with only numeric columns and cluster assignment
numeric_columns <- clust_fb %>% select(cluster, where(is.numeric))

# Aggregate the results to view the cluster summary
cluster_summary <- aggregate(. ~ cluster, data=numeric_columns, mean)
cluster_summary

```



```{r cluster-visualization}
# Visualize the clustering
fviz_cluster(list(data = normalized_fb, cluster = k$cluster))
```



```{r confusion-matrix}
#library(caret)
#clust_fb$cluster <- as.factor(clust_fb$cluster)
#confusionMatrix(clust_fb$cluster, clust_fb$Pos)
```



```{r tables}
# Format a table relating Games Started and cluster
gs_table <- table(clust_fb$cluster, clust_fb$GS)
gs_prop <- prop.table(gs_table, margin=1) * 100
gs_prop_formatted <- apply(gs_prop, c(1, 2), function(x) paste0(round(x, 1), "%"))
gs_prop_formatted


#fp_table <- table(clust_fb$cluster, clust_fb$FantasyPoints)
#fp_prop <- prop.table(fp_table, margin=1) * 100
#fp_prop_formatted <- apply(fp_prop, c(1, 2), function(x) paste0(round(x, 1), "%"))
#fp_prop_formatted

#fpG_table <- table(clust_fb$cluster, clust_fb$FantasyPoints_gm)
#fpG_prop <- prop.table(fpG_table, margin=1) * 100
#fpG_prop_formatted <- apply(fpG_prop, c(1, 2), function(x) paste0(round(x, 1), "%"))
#fpG_prop_formatted
```



```{r boxplots}
# ALL X AXIS ARE THE CLUSTER

# RECEIVING YARDS PER GAME
ggplot(clust_fb, aes(x=factor(cluster), y=ReceivingYds_gm, fill=factor(cluster))) + 
  geom_boxplot() + 
  labs(x="Cluster", y="Receiving Yards per Game")

# GAMES STARTED 
ggplot(clust_fb, aes(x=factor(cluster), y=GS, fill=factor(cluster))) + 
  geom_boxplot() + 
  labs(x="Cluster", y="Games Started")

# PASSING YARDS PER GAME
ggplot(clust_fb, aes(x=factor(cluster), y=PassingYds_gm, fill=factor(cluster))) + 
  geom_boxplot() + 
  labs(x="Cluster", y="Passing Yards per Game")

# FANTASY POINTS PER GAME
ggplot(clust_fb, aes(x=factor(cluster), y=FantasyPoints_gm, fill=factor(cluster))) + 
  geom_boxplot() + 
  labs(x="Cluster", y="Fantasy Points per Game")

# TOTAL FANTASY POINTS
ggplot(clust_fb, aes(x=factor(cluster), y=FantasyPoints, fill=factor(cluster))) + 
  geom_boxplot() + 
  labs(x="Cluster", y="Fantasy Points")
```


